//
//  DemoSeeder.swift
//  Rclone GUI — Core
//
//  Seeds realistic, privacy-safe demo data so the App Store screenshots show
//  the real app *in use* (Guideline 2.3.3) without exposing any real account.
//
//  Activated ONLY when the app is launched with `--seed-demo` (or the
//  SEED_DEMO=1 environment variable). Compiled in DEBUG builds only, so it
//  can never run in a production App Store binary.
//
//  What it sets up:
//    • A plaintext rclone.conf with one *browsable* local remote (`iPhone`,
//      an alias rooted at a seeded demo tree) plus a curated set of cloud
//      remotes (B2, S3/Wasabi, Drive, Dropbox, OneDrive, SFTP) and one
//      `crypt` remote — enough to populate the Files dashboard with colored
//      backend chips and a crypt badge.
//    • A demo file tree (sparse files with realistic names/sizes/dates) so
//      the folder browser and file detail screens show real content.
//    • SwiftData rows (pinned/recent locations, transfers, photo-sync assets)
//      so Home reads as a lively "control center".
//
//  Everything is idempotent and confined to the app's own container.
//

#if DEBUG
import Foundation
import SwiftData

@MainActor
enum DemoSeeder {

    /// True when the current launch asked for demo seeding.
    static var isRequested: Bool {
        CommandLine.arguments.contains("--seed-demo")
            || ProcessInfo.processInfo.environment["SEED_DEMO"] == "1"
    }

    /// Entry point — call once, early, before the engine reads the config.
    static func seedIfRequested(container: ModelContainer) async {
        guard isRequested else { return }

        // Skip onboarding so screenshots land on real, in-use surfaces.
        UserDefaults.standard.set(true, forKey: "hasCompletedOnboarding")

        let demoRoot = makeDemoFiles()
        let conf = rcloneConf(localRoot: demoRoot)

        do {
            try await ConfigStore.shared.save(Data(conf.utf8))
            // The engine may not have initialised yet; reload is best-effort.
            try? await RcloneCore.shared.reloadConfigurationFromStore()
        } catch {
            NSLog("[DemoSeeder] config save failed: \(error)")
        }

        seedSwiftData(container.mainContext)

        // Nudge the long-lived tabs to reload from the freshly-seeded config.
        NotificationCenter.default.post(name: .rcloneConfigurationDidChange, object: nil)
    }

    // MARK: - rclone.conf

    /// A crypt password pre-obscured with `rclone obscure` (value is a throwaway
    /// demo passphrase, never a real secret).
    private static let demoCryptPassword = "Rn_xRfYB5FRLR-msTU_cE7b_vzokbuoxS2J0k02_8NVD767m"

    private static func rcloneConf(localRoot: URL) -> String {
        """
        # Demo configuration generated by DemoSeeder for App Store screenshots.
        # Contains NO real credentials — cloud remotes are placeholders used
        # only to populate the UI; the `iPhone` alias is the one browsable root.

        [iPhone]
        type = alias
        remote = \(localRoot.path)

        [Backblaze B2]
        type = b2
        account = 003a1b2c3d4e5f60000000001
        key = K003exampleexampleexampleexampleEXA

        [Wasabi S3]
        type = s3
        provider = Wasabi
        access_key_id = WAS0EXAMPLEACCESSKEY00
        secret_access_key = wAsAbIeXaMpLeSeCrEtKeY00000000000000000000
        endpoint = s3.eu-central-2.wasabisys.com

        [Google Drive]
        type = drive
        scope = drive
        token = {"access_token":"demo","token_type":"Bearer","expiry":"2099-01-01T00:00:00Z"}

        [Dropbox]
        type = dropbox
        token = {"access_token":"demo","token_type":"bearer","expiry":"2099-01-01T00:00:00Z"}

        [OneDrive]
        type = onedrive
        drive_type = personal
        token = {"access_token":"demo","token_type":"Bearer","expiry":"2099-01-01T00:00:00Z"}

        [NAS SFTP]
        type = sftp
        host = nas.maison.lan
        user = vitaly
        port = 22

        [Photos chiffré]
        type = crypt
        remote = iPhone:Photos
        password = \(demoCryptPassword)
        filename_encryption = standard
        directory_name_encryption = true

        [Vault Cloud]
        type = crypt
        remote = iPhone:Vault
        password = \(demoCryptPassword)
        filename_encryption = standard
        directory_name_encryption = true

        """
    }

    // MARK: - Demo file tree

    private struct DemoFile {
        let path: String          // relative to demo root
        let bytes: Int64          // logical size (sparse on disk)
        let daysAgo: Double       // modification time offset
    }

    private static let demoTree: [DemoFile] = [
        // Photos/
        .init(path: "Photos/IMG_4821.HEIC", bytes: 3_412_000, daysAgo: 1.2),
        .init(path: "Photos/IMG_4822.HEIC", bytes: 4_118_400, daysAgo: 1.2),
        .init(path: "Photos/IMG_4905.HEIC", bytes: 2_903_100, daysAgo: 2.4),
        .init(path: "Photos/IMG_5012.HEIC", bytes: 3_770_500, daysAgo: 3.1),
        .init(path: "Photos/Panorama-Bali.JPG", bytes: 8_742_000, daysAgo: 5.0),
        .init(path: "Photos/Coucher-de-soleil.JPG", bytes: 5_204_800, daysAgo: 5.0),
        // Vidéos/
        .init(path: "Vidéos/Vacances-Bali-2026.MOV", bytes: 1_843_200_000, daysAgo: 5.0),
        .init(path: "Vidéos/Anniversaire-Léa.MP4", bytes: 642_500_000, daysAgo: 12.0),
        .init(path: "Vidéos/Surf-Uluwatu.MP4", bytes: 318_900_000, daysAgo: 6.0),
        // Documents/
        .init(path: "Documents/Rapport-Q2-2026.pdf", bytes: 243_700, daysAgo: 0.4),
        .init(path: "Documents/Facture-2026-0142.pdf", bytes: 88_200, daysAgo: 2.0),
        .init(path: "Documents/Budget-prévisionnel.xlsx", bytes: 52_400, daysAgo: 4.0),
        .init(path: "Documents/Contrat-prestation.pdf", bytes: 176_900, daysAgo: 8.0),
        .init(path: "Documents/Notes-réunion.md", bytes: 6_120, daysAgo: 0.2),
        // Musique/
        .init(path: "Musique/Podcast-EP42.m4a", bytes: 58_300_000, daysAgo: 1.0),
        .init(path: "Musique/Set-live-2026.mp3", bytes: 132_000_000, daysAgo: 9.0),
        // Sauvegardes/
        .init(path: "Sauvegardes/backup-2025-12.zip", bytes: 4_311_000_000, daysAgo: 30.0),
        // top-level
        .init(path: "Lisez-moi.txt", bytes: 1_280, daysAgo: 14.0),
    ]

    @discardableResult
    private static func makeDemoFiles() -> URL {
        let fm = FileManager.default
        let root = AppGroup.containerURL.appending(path: "DemoFiles", directoryHint: .isDirectory)
        for file in demoTree {
            let url = root.appending(path: file.path)
            let dir = url.deletingLastPathComponent()
            try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
            if !fm.fileExists(atPath: url.path) {
                if file.path.hasSuffix(".txt") || file.path.hasSuffix(".md") {
                    let body = "Rclone GUI — fichier de démonstration.\nCe contenu sert uniquement aux captures App Store.\n"
                    try? Data(body.utf8).write(to: url)
                } else {
                    // Sparse file: realistic logical size, ~zero bytes on disk.
                    fm.createFile(atPath: url.path, contents: nil)
                    if let handle = try? FileHandle(forWritingTo: url) {
                        try? handle.truncate(atOffset: UInt64(max(file.bytes, 0)))
                        try? handle.close()
                    }
                }
            }
            let modDate = Date().addingTimeInterval(-file.daysAgo * 86_400)
            try? fm.setAttributes([.modificationDate: modDate], ofItemAtPath: url.path)
        }
        return root
    }

    // MARK: - SwiftData (Home dashboard liveliness)

    private static func seedSwiftData(_ context: ModelContext) {
        // Idempotent: only seed an empty store.
        let existing = (try? context.fetchCount(FetchDescriptor<SavedLocation>())) ?? 0
        guard existing == 0 else { return }

        // Pinned + recent locations.
        let pinned: [(String, String, String, Int)] = [
            ("iPhone", "Photos", "Photos", 0),
            ("Google Drive", "Projets/2026", "Projets 2026", 1),
        ]
        for (remote, path, name, idx) in pinned {
            context.insert(SavedLocation(
                kind: .pinned, remote: remote, path: path, displayName: name,
                createdAt: Date().addingTimeInterval(-Double(idx + 3) * 86_400),
                lastOpenedAt: Date().addingTimeInterval(-Double(idx + 1) * 3_600),
                openCount: 12 - idx, sortIndex: idx
            ))
        }
        let recent: [(String, String, String, Double)] = [
            ("iPhone", "Videos", "Videos", 0.4),
            ("Wasabi S3", "archives", "archives", 1.5),
            ("NAS SFTP", "media/films", "films", 6.0),
        ]
        for (remote, path, name, hrs) in recent {
            context.insert(SavedLocation(
                kind: .recent, remote: remote, path: path, displayName: name,
                lastOpenedAt: Date().addingTimeInterval(-hrs * 3_600)
            ))
        }

        // Transfers — two running (drives the "transferts en cours" banner),
        // plus history for the activity metrics.
        let t1 = Transfer(
            kind: .upload, sourceRemote: nil, sourcePath: "Vacances-Bali-2026.MOV",
            destinationRemote: "Backblaze B2", destinationPath: "videos/Vacances-Bali-2026.MOV",
            displayName: "Vacances-Bali-2026.MOV", sourceKind: .photoLibrary,
            bytesTotal: 1_843_200_000, status: .running
        )
        t1.bytesTransferred = 1_186_300_000
        let t2 = Transfer(
            kind: .upload, sourceRemote: nil, sourcePath: "IMG_5012.HEIC",
            destinationRemote: "Photos chiffré", destinationPath: "IMG_5012.HEIC",
            displayName: "IMG_5012.HEIC", sourceKind: .photoLibrary,
            bytesTotal: 3_770_500, status: .running
        )
        t2.bytesTransferred = 2_450_000
        context.insert(t1)
        context.insert(t2)

        let completedNames = [
            "IMG_4821.HEIC", "IMG_4822.HEIC", "Rapport-Q2-2026.pdf",
            "Panorama-Bali.JPG", "Set-live-2026.mp3", "Facture-2026-0142.pdf",
        ]
        for (i, name) in completedNames.enumerated() {
            let t = Transfer(
                kind: .upload, sourcePath: name,
                destinationRemote: "Backblaze B2", destinationPath: "auto/\(name)",
                displayName: name, sourceKind: .photoLibrary,
                bytesTotal: Int64(2_000_000 + i * 900_000), status: .completed
            )
            t.bytesTransferred = t.bytesTotal
            t.finishedAt = Date().addingTimeInterval(-Double(i + 1) * 1_800)
            t.startedAt = Date().addingTimeInterval(-Double(i + 1) * 1_900)
            context.insert(t)
        }
        let failed = Transfer(
            kind: .download, sourceRemote: "Google Drive", sourcePath: "Projets/maquette.sketch",
            destinationPath: "maquette.sketch", displayName: "maquette.sketch",
            sourceKind: .remote, bytesTotal: 142_000_000, status: .failed
        )
        failed.bytesTransferred = 38_000_000
        failed.lastError = "Quota dépassé sur le remote distant"
        context.insert(failed)

        // Photo-sync assets — a mostly-complete backup batch.
        for i in 0..<48 {
            let asset = PhotoSyncAsset(
                localIdentifier: "demo-asset-\(i)",
                mediaType: i % 7 == 0 ? "video" : "image",
                creationDate: Date().addingTimeInterval(-Double(i) * 3_600)
            )
            asset.byteCount = Int64(2_400_000 + (i % 5) * 1_300_000)
            if i < 42 {
                asset.statusRaw = PhotoSyncStatus.completed.rawValue
                asset.completedAt = Date().addingTimeInterval(-Double(i) * 600)
                asset.remotePathsJSON = "[\"Backblaze B2:photos/IMG_\(4000 + i).HEIC\"]"
            } else {
                asset.statusRaw = PhotoSyncStatus.pending.rawValue
            }
            context.insert(asset)
        }

        try? context.save()
    }
}
#endif
